version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: svetlanaf/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
      - ./data:/app/data/
  frontend:
    env_file: .env
    image: svetlanaf/foodgram_frontend
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
      - static:/static
  gateway:
    image: svetlanaf/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/app/media/
